# Build Docker image using Azure Pipelines

jobs:
- job: PlanningPokerDocker
  displayName: PlanningPoker Docker
  dependsOn: PlanningPokerApp

  pool:
    vmImage: ubuntu-latest

  workspace:
    clean: all

  variables:
    PlanningPokerDockerImageTag: 'b$(Build.BuildId)'

  steps:
  - task: DownloadBuildArtifacts@0
    displayName: 'Download artifact: web'
    inputs:
      artifactName: web
      downloadPath: $(System.BinariesDirectory)

  - task: ExtractFiles@1
    displayName: Extract web.zip
    inputs:
      archiveFilePatterns: $(System.BinariesDirectory)/web/web.zip
      destinationFolder: $(System.DefaultWorkingDirectory)/docker/app

  - task: Docker@2
    displayName: Build Docker image
    inputs:
      command: build
      Dockerfile: docker/Dockerfile
      repository: $(DockerRepositoryName)
      tags: $(PlanningPokerDockerImageTag)

  - pwsh: './docker/test/RunTests.ps1 -PlanningPokerImageTag $env:PLANNINGPOKERDOCKERIMAGETAG -TestResultPath "$env:BUILD_STAGINGDIRECTORY/PlanningPokerDocker.TestResult.xml"'
    displayName: 'Run Docker container tests'

  - task: PublishTestResults@2
    displayName: Public Docker container test results
    inputs:
      testResultsFormat: NUnit
      searchFolder: $(Build.StagingDirectory)
      testResultsFiles: PlanningPokerDocker.TestResult.xml
      testRunTitle: Planning Poker - Docker
    condition: succeededOrFailed()

  - task: Docker@2
    displayName: Push Docker image
    inputs:
      command: push
      containerRegistry: $(DockerRegistryEndpointName)
      repository: $(DockerRepositoryName)
      tags: $(PlanningPokerDockerImageTag)
